//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazinElectronic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int IDOrder { get; set; }
        public bool Bill_status { get; set; }
        public System.DateTime Payment_date { get; set; }
        public decimal Bill_amount { get; set; }
        public string DetaliiBill { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
