//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazinElectronic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategorieProduse> CategorieProduses { get; set; }
        public virtual DbSet<Costumer> Costumers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Produse> Produses { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Inventar> Inventars { get; set; }
    }
}
